name = input("Як тебе звуть?\n")
print(f"привіт, {name} я чат cat.\nПриємно познайомитися?")
vik = input("скільки тобі років?\n")
color = input("який твій улюблений колір?")
print(f"ой, {color} - це чудовий колір")
print(f"{name} любить {color}, їй {vik} років")